# Generated by Django 4.2.7 on 2023-11-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reteta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('text_reteta', models.CharField(max_length=255)),
                ('timp_executie', models.CharField(max_length=100)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
                ('data_actualizare', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
