# Generated by Django 4.2.7 on 2023-12-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reteta',
            name='text_reteta',
            field=models.CharField(max_length=1000),
        ),
    ]
